// flow-typed signature: 8442b81f4e78592188cff840fc2659f3
// flow-typed version: <<STUB>>/strman_vx.x.x/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'strman'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'strman' {
  declare module.exports: any;
}
